/**
 * `index.md` — the vault's front page.
 *
 * Regenerated after every transition (spec §9 step 10), so it must be a pure
 * function of vault state: no clock, no counters, no scan-order dependence.
 * Anything non-deterministic here would put a diff in every commit and make the
 * git history unreadable, which is the same failure the note serializer guards
 * against.
 */
import { TICKET_STATES } from '../domain/states.js';
import type { FeatureNote, TicketNote } from '../domain/types.js';
import { atomicWrite } from './atomic.js';
import type { VaultPaths } from './paths.js';
import type { Storage } from './storage.js';

export interface IndexEntry {
  readonly feature: FeatureNote;
  readonly tickets: readonly TicketNote[];
}

/** The markdown for `index.md`. Pure — same input, same bytes, always. */
export function buildIndex(entries: readonly IndexEntry[]): string {
  const sorted = [...entries].sort((a, b) =>
    a.feature.frontmatter.slug < b.feature.frontmatter.slug ? -1 : 1,
  );

  const lines: string[] = [
    '# Factory Index',
    '',
    'Regenerated by the orchestrator after every transition. Do not edit by hand —',
    'the next write will overwrite it.',
    '',
    '## Features',
    '',
  ];

  if (sorted.length === 0) {
    lines.push('_No features yet._', '');
  } else {
    lines.push('| Feature | Status | Tickets | By state |', '| --- | --- | --- | --- |');
    for (const { feature, tickets } of sorted) {
      const { slug, title, status } = feature.frontmatter;
      const link = `[${escapeCell(title)}](work/features/${slug}/feature.md)`;
      lines.push(
        `| ${link} | ${status} | ${tickets.length} | ${byState(tickets)} |`,
      );
    }
    lines.push('');
  }

  const ticketTotal = sorted.reduce((sum, entry) => sum + entry.tickets.length, 0);
  lines.push('## Totals', '', `- Features: ${sorted.length}`, `- Tickets: ${ticketTotal}`, '');

  return lines.join('\n');
}

/**
 * Read the whole vault, rebuild `index.md`, and write it atomically.
 * Returns what was written so a caller can log or assert on it.
 */
export async function regenerateIndex(storage: Storage, paths: VaultPaths): Promise<string> {
  const features = await storage.listFeatures();
  const entries: IndexEntry[] = [];

  for (const feature of features) {
    entries.push({ feature, tickets: await storage.listTickets(feature.frontmatter.slug) });
  }

  const markdown = buildIndex(entries);
  await atomicWrite(paths.indexFile(), markdown);
  return markdown;
}

/**
 * `backlog 2, in_progress 1, done 1` — counted in `TICKET_STATES` order so the
 * string does not depend on which ticket happened to be read first.
 */
function byState(tickets: readonly TicketNote[]): string {
  const counts = new Map<string, number>();
  for (const ticket of tickets) {
    const status = ticket.frontmatter.status;
    counts.set(status, (counts.get(status) ?? 0) + 1);
  }

  const parts = TICKET_STATES.filter((state) => counts.has(state)).map(
    (state) => `${state} ${counts.get(state) ?? 0}`,
  );
  return parts.length > 0 ? parts.join(', ') : '—';
}

/**
 * Make a value safe to sit inside a markdown table cell.
 *
 * A `|` splits the cell in two; a newline ends the whole row and turns the rest
 * of the title into a malformed table line. Titles come from agent output, so
 * both are reachable. Whitespace runs are flattened to a single space rather
 * than escaped, because there is no escape for a newline in a table cell.
 */
function escapeCell(value: string): string {
  return value.replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');
}
