/**
 * `NEEDS_HUMAN.md` — the vault's to-do list for its operator.
 *
 * Sibling of `index-md.ts` and built to the same rule: a pure function of vault
 * state, no clock and no scan-order dependence, so regenerating it twice from
 * an unchanged vault produces identical bytes and the git history stays
 * readable.
 *
 * It exists because `status: needs_human` is spread across a directory tree.
 * A human who has to open every feature file to find what is waiting on them
 * will stop reading the vault, and then the checkpoints stop working.
 */
import type { PauseFields } from '../domain/types.js';

/** One line of the file: an item that is parked, and what will unpark it. */
export interface NeedsHumanItem extends PauseFields {
  readonly id: string;
  readonly title: string;
  readonly kind: 'feature' | 'ticket';
  /** Vault-relative path, so the link works when Obsidian opens the file. */
  readonly path: string;
}

const NONE = '—';

/**
 * The markdown for `NEEDS_HUMAN.md`.
 *
 * Sorted by id rather than by pause time: the same set of parked items must
 * always render the same way, and `paused_at` is close enough to a clock read
 * to make the output depend on dispatch order.
 */
export function buildNeedsHuman(items: readonly NeedsHumanItem[]): string {
  const sorted = [...items].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  const lines: string[] = [
    '# Needs Human',
    '',
    'Regenerated by the orchestrator whenever the needs-human set changes. Do not edit by hand —',
    'the next write will overwrite it.',
    '',
  ];

  if (sorted.length === 0) {
    lines.push('_Nothing is waiting on you._', '');
    return lines.join('\n');
  }

  lines.push(
    `${sorted.length} item${sorted.length === 1 ? '' : 's'} waiting.`,
    '',
    '| Item | Kind | Why | Approve moves it to | Reject moves it to | Paused at |',
    '| --- | --- | --- | --- | --- | --- |',
  );

  for (const item of sorted) {
    lines.push(
      `| [${escapeCell(item.id)}](${item.path}) | ${item.kind} | ${escapeCell(
        item.pause_reason ?? 'unspecified',
      )} | ${item.resume_to ?? NONE} | ${item.reject_to ?? NONE} | ${item.paused_at ?? NONE} |`,
    );
  }

  lines.push('');

  for (const item of sorted) {
    lines.push(
      `## ${item.id} — ${escapeInline(item.title)}`,
      '',
      `- **Why:** ${item.pause_reason ?? 'unspecified'}`,
      `- **Detail:** ${escapeInline(item.pause_detail ?? NONE)}`,
      `- **Note:** \`${item.path}\``,
      '',
      '```',
      item.resume_to === null
        ? `# this pause has no resume target; fix the item and re-run, or reject it`
        : `factory approve ${item.id} "why this is fine"`,
      item.reject_to === null
        ? `# this pause has no reject target; approving is the only way forward`
        : `factory reject ${item.id} "what to change"`,
      '```',
      '',
    );
  }

  return lines.join('\n');
}

/**
 * Make a value safe inside a markdown table cell. A `|` splits the cell and a
 * newline ends the row — both reachable, because these strings come from agent
 * output. Same treatment as `index-md.ts` uses, for the same reason.
 */
function escapeCell(value: string): string {
  return value.replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');
}

/** Outside a table only newlines matter; a pipe is harmless there. */
function escapeInline(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}
